[build-system]
requires = [
    "setuptools>=80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.DelegationOfParentalAuthority"
version = "1.0"
description = "Delegation of parental authority"
readme = "README.md"
authors = [
    { name = "Amanda Sauber", email = "alsauber@mnlegalservices.org" },
]
dependencies = [
    "docassemble.AssemblyLine @ git+https://github.com/SuffolkLITLab/docassemble-AssemblyLine.git@main",
    "docassemble.GithubFeedbackForm @ git+https://github.com/SuffolkLITLab/docassemble-GithubFeedbackForm.git@main",
    "docassemble.InterviewStats @ git+https://github.com/SuffolkLITLab/docassemble-InterviewStats.git@date-filter",
]

[project.urls]
Homepage = "https://courtformsonline.org"

[tool.setuptools.packages.find]
where = [
    ".",
]
